version: "3.5"

services:
  php:
    build:
      context: ./.misc/docker/php
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: bash -c "composer install --no-interaction --no-dev && php /var/www/run.php"